# Generated by Django 5.2.3 on 2025-08-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderdetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
