# Generated by Django 5.2.3 on 2025-07-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('method', models.CharField(choices=[('upi_id', 'upi_id'), ('upi_app', 'upi_app'), ('bank', 'bank')], max_length=10)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'COMPLETED'), ('N', 'NOTCOMPLETED')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
