# Generated by Django 5.2.3 on 2025-08-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier')], default='Supplier', max_length=8),
            preserve_default=False,
        ),
    ]
