# Generated by Django 5.2.3 on 2025-08-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item',
            new_name='product_name',
        ),
    ]
