# Generated by Django 5.2.3 on 2025-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_item_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_des',
            field=models.CharField(choices=[('all', 'All'), ('Featured', 'Featured'), ('special', 'special')], default='all', max_length=10),
        ),
    ]
