# Generated by Django 5.2.3 on 2025-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default='12a0a0d1-f894-4a55-aeee-8b0502bc5da0'),
            preserve_default=False,
        ),
    ]
