# Generated by Django 5.2.3 on 2025-08-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
    ]
