# Generated by Django 5.2.3 on 2025-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(null=True),
        ),
    ]
